### PR TITLE
prebuild as importable

### PR DESCRIPTION
**Pull request by beijaflor**
This is due to make Vue2-timepicker importable without any dependency.
Added Pre-Build and trans-piled code from source and point it as entry-point of package.
You can import `src/vue-timepicker` directory if you want start with original source instead of compiled code.

---

ref: https://github.com/phoenixwong/vue2-timepicker/issues/15

- [x] rename `*.prod.*` to `*.demo.*`
- [x] add `prebuild` task
- [x] add prebuild js as a entrypoint

### CODE REVIEW

**Comment by beijaflor** [comment]
@phoenixwong 
Please review and feedback, please.

**Comment by xxRockOnxx** [comment]
Hello, this repo is dead or no longer maintained. You can submit a PR to my branch instead if you saw the same problem. I am trying to maintain it as long as I could.

**Comment by runrog** [comment]
+1 this PR fixes an annoying import issues in this repo.

**Comment by phoenixwong** [comment]
Sorry for the long wait. Please give the latest release [v0.2.0](https://github.com/phoenixwong/vue2-timepicker/releases/tag/v0.2.0) a try. [#66]

**Pull request closed without merging**
